name = "SimpleSplines"
uuid = "ac480f6c-9a94-4d53-a283-9db69f109154"
authors = ["Michael Kraus"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
