module SimpleSplines

    using ContinuumArrays
    using FFTW
    using LinearAlgebra
    using QuadratureRules
    using Random
    using SparseArrays
    using StaticArrays

    import Base: *
    # QuasiAdjoint is not referenced directly, but the code generated by @simplify
    # expands to a QuasiAdjoint method in this module, so it must be in scope
    import ContinuumArrays: Mul, QMul2, QuasiAdjoint, (..), @simplify

    # extended rather than defined here, so that the packages of the ecosystem share one
    # generic function per accessor. `degree`, `nodes`, `nnodes` and `order` belong to
    # GeometricBase, `grid` to ContinuumArrays, and `nbasis` to CompactBasisFunctions,
    # whose `Basis` hierarchy the spline bases join.
    import GeometricBase: basis, degree, nnodes, nodes, order
    import CompactBasisFunctions: Basis, nbasis

    export Basis, basis, nbasis, degree, nodes, nnodes, order, grid

    export Mesh, UniformMesh, GradedMesh, RandomMesh
    export breakpoints, ncells, domainlength, cellbounds, meshwidth

    include("knots.jl")

    export PeriodicBSplineBasis, PeriodicBSplineDerivative
    export knotvector, evaluate, mesh

    include("bspline.jl")

    export MassOperator, CirculantMass, FactorizedMass, mass_operator, mass_solve!

    include("mass.jl")

    export SplineQuadrature, quadrature_order
    export quadrature_nodes, quadrature_weights, basis_values
    export mass_matrix, mass_factorization, stiffness_matrix, derivative_matrix,
           mixed_matrix, weighted_matrix, basis_integrals, l2_projection, l2_projection!

    include("quadrature.jl")

end
