module SimpleSplines

using BandedMatrices
using ContinuumArrays
using FFTW
using LinearAlgebra
using QuadratureRules
using Random
using SparseArrays

import Base: *

# QuasiAdjoint is not referenced directly, but the code generated by @simplify
# expands to a QuasiAdjoint method in this module, so it must be in scope
import ContinuumArrays: Mul, QMul2, QuasiAdjoint, (..), @simplify

# The interval and product-domain types the bases report through `domain`. Imported by name
# rather than brought in with `using`, so that it is visible which package each of them comes
# from -- `..` above and `ClosedInterval` here are the *same* IntervalSets binding, reached
# through two different re-exporters, and an explicit import is what makes that checkable.
import DomainSets: ClosedInterval, ProductDomain, leftendpoint, rightendpoint

# extended rather than defined here, so that the packages of the ecosystem share one
# generic function per accessor. `degree`, `nodes`, `nnodes` and `order` belong to
# GeometricBase, `grid` to ContinuumArrays, and `nbasis` to CompactBasisFunctions,
# whose `Basis` hierarchy the spline bases join.
import GeometricBase: basis, degree, nnodes, nodes, order
import CompactBasisFunctions: Basis, nbasis

export Basis, basis, nbasis, degree, nodes, nnodes, order, grid

# Re-exported so that `using SimpleSplines` is enough to write a domain. Every constructor
# here takes one, and `UniformMesh(16, -10 .. 10)` failing with `.. not defined` would be a
# poor first experience of the package.
export ..

export Mesh, UniformMesh, GradedMesh, RandomMesh, GeneralMesh
export breakpoints, ncells, domain, domainlength, meshwidth
export leftendpoint, rightendpoint

include("mesh.jl")

export BoundaryCondition
export Periodic, Free, Dirichlet, Neumann, Natural, Robin, Constraint
export boundary_conditions, constraint_coefficients, nconstraints, constraint_order

include("boundary.jl")

export AbstractBSplineBasis, BSplineBasis, PeriodicBSplineBasis
export BSplineDerivative, PeriodicBSplineDerivative
export knotvector, evaluate, evaluate_all, evaluate_all!, mesh
export boundary, basis_index, findcell, local_width, polynomial_reproduction

include("bspline.jl")

export MassOperator, CirculantMass, FactorizedMass, BandedMass, mass_operator, mass_solve!

include("mass.jl")

export RecombinedBSplineBasis, recombination_matrix

include("recombined.jl")

export SplineQuadrature, quadrature_order, local_indices
export quadrature_nodes, quadrature_weights, basis_values
export mass_matrix, mass_factorization, stiffness_matrix, derivative_matrix,
       mixed_matrix, weighted_matrix, basis_integrals, l2_projection, l2_projection!

include("quadrature.jl")

export TensorProductBasis, TensorProductQuadrature, KroneckerMass, ⊗
export bases, quadratures, mass_factors, contract
export quadrature_sample, quadrature_grid_size

include("tensorproduct.jl")

export Spline, SplineDerivative, coefficients, derivative

include("spline.jl")

end
